name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          ini-values: post_max_size=256M, log_errors=1
          coverage: xdebug
          tools: phpstan
      - name: Run Composer
        run: composer install  
      - name: Run PHPStan
        run: phpstan analyse src tests               
      - name: Run test suite
        run: vendor/bin/phpunit
      - name: Run test coverage
        run: vendor/bin/phpunit --verbose --coverage-text
      - name: Run test coverage.xml
        run: vendor/bin/phpunit --coverage-clover coverage.xml         
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml        